{{- if .Values.issuer.enabled }}
{{- $clusterIssuerEnabled := .Values.issuer.cluster }}
{{- if hasKey .Values.jxRequirements "environments" }}
{{- range $key, $val := .Values.jxRequirements.environments }}
{{- if hasKey $val "ingress" }}
{{- if $val.ingress.domain }}
{{- if hasKey $val "ingress.tls" }}
{{- if $val.ingress.tls.enabled }}
{{- if $val.ingress.tls.production }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "tls-{{ $val.ingress.domain | replace "." "-" }}-p"
  labels:
    jenkins.io/letsencrypt-service: production
spec:
  secretName: "tls-{{ $val.ingress.domain | replace "." "-" }}-p"
  issuerRef:
    name: letsencrypt-prod
{{- if $clusterIssuerEnabled }}
kind: ClusterIssuer
{{- end }}
commonName: "*.{{ $val.ingress.domain }}"
dnsNames:
  - "*.{{ $val.ingress.domain }}"
  - "{{ $val.ingress.domain }}"

---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}